<?php

namespace SBC\AWAPartnersBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->createQueryBuilder('project')
            ->leftJoin('project.pictures', 'pictures')
            ->addSelect('pictures')
            ->leftJoin('project.projecType', 'projecType')
            ->addSelect('projecType')
            ->leftJoin('project.client', 'client')
            ->addSelect('client')
            ->getQuery();
        return $query->getResult();
    }

    public function find($id, $lockMode = null, $lockVersion = null)
    {
        $query = $this->createQueryBuilder('project')
            ->leftJoin('project.pictures', 'pictures')
            ->addSelect('pictures')
            ->leftJoin('project.projecType', 'projecType')
            ->addSelect('projecType')
            ->where('project.id = ?1')
            ->getQuery();
        $query->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }
}
